import fs from 'node:fs/promises';
import solc from 'solc';
import { build } from 'esbuild';
import { keccak256 } from 'ethers';

const source = await fs.readFile('contracts/ScopeStamp.sol', 'utf8');
const input = { language: 'Solidity', sources: { 'ScopeStamp.sol': { content: source } },
  settings: { optimizer: { enabled: true, runs: 200 }, evmVersion: 'shanghai',
    outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode.object'] } } } };
const output = JSON.parse(solc.compile(JSON.stringify(input)));
const errors = (output.errors || []).filter(e => e.severity === 'error');
if (errors.length) throw Error(errors.map(e => e.formattedMessage).join('\n'));
const artifact = output.contracts['ScopeStamp.sol'].ScopeStamp;
await fs.mkdir('build', { recursive: true });
await fs.writeFile('build/ScopeStamp.json', JSON.stringify({ compiler: solc.version(), ...artifact }, null, 2));
await fs.writeFile('src/registry.js', `// Generated by scripts/build.js; pin the locally compiled registry runtime.\nexport const REGISTRY_RUNTIME_HASH = '${keccak256('0x' + artifact.evm.deployedBytecode.object)}';\n`);
await fs.mkdir('dist', { recursive: true });
await fs.copyFile('ui/index.html', 'dist/index.html');
await fs.copyFile('ui/style.css', 'dist/style.css');
await build({ entryPoints: ['ui/app.js'], bundle: true, outfile: 'dist/app.js', format: 'esm', platform: 'browser', target: 'es2022' });
console.log(JSON.stringify({ compiled: true, compiler: solc.version(), bytecodeBytes: artifact.evm.bytecode.object.length / 2, frontendBuilt: true }));
